"""
Markdown formatter for structured notes.
"""

from datetime import datetime
from typing import Optional
from .processor import StructuredNote


class MarkdownFormatter:
    """Format structured notes as Markdown."""
    
    CATEGORY_ICONS = {
        "idea": "💡",
        "todo": "✅",
        "meeting": "👥",
        "inspiration": "✨",
        "memo": "📝",
    }
    
    PRIORITY_ICONS = {
        "high": "🔴",
        "medium": "🟡",
        "low": "🟢",
    }
    
    SENTIMENT_ICONS = {
        "excited": "🤩",
        "hesitant": "🤔",
        "urgent": "⚡",
        "calm": "😌",
        "neutral": "😐",
    }
    
    def format(self, note: StructuredNote, created_at: Optional[datetime] = None) -> str:
        """
        Format note as Markdown.
        
        Args:
            note: Structured note
            created_at: Optional creation timestamp
            
        Returns:
            str: Markdown formatted note
        """
        lines = []
        
        # Header with icon
        icon = self.CATEGORY_ICONS.get(note.category, "📝")
        priority_icon = self.PRIORITY_ICONS.get(note.priority, "⚪")
        sentiment_icon = self.SENTIMENT_ICONS.get(note.sentiment, "")
        
        lines.append(f"# {icon} {note.title}")
        lines.append("")
        
        # Metadata
        lines.append("## Metadata")
        lines.append("")
        lines.append(f"- **Category**: {note.category}")
        lines.append(f"- **Priority**: {priority_icon} {note.priority}")
        lines.append(f"- **Sentiment**: {sentiment_icon} {note.sentiment}")
        lines.append(f"- **Tags**: {', '.join(f'`{tag}`' for tag in note.tags)}")
        if created_at:
            lines.append(f"- **Created**: {created_at.strftime('%Y-%m-%d %H:%M')}")
        lines.append("")
        
        # Summary
        lines.append("## Summary")
        lines.append("")
        lines.append(note.summary)
        lines.append("")
        
        # Key Points
        if note.key_points:
            lines.append("## Key Points")
            lines.append("")
            for point in note.key_points:
                lines.append(f"- {point}")
            lines.append("")
        
        # Action Items
        if note.action_items:
            lines.append("## Action Items")
            lines.append("")
            for i, item in enumerate(note.action_items, 1):
                lines.append(f"{i}. [ ] {item}")
            lines.append("")
        
        # Footer
        lines.append("---")
        lines.append(f"*Generated by Voice Notes Assistant*")
        
        return "\n".join(lines)
    
    def format_simple(self, note: StructuredNote) -> str:
        """
        Format note in simple compact format.
        
        Args:
            note: Structured note
            
        Returns:
            str: Simple markdown
        """
        icon = self.CATEGORY_ICONS.get(note.category, "📝")
        priority = self.PRIORITY_ICONS.get(note.priority, "")
        
        lines = [
            f"## {priority} {icon} {note.title}",
            "",
            f"**{note.category.upper()}** | {', '.join(note.tags)}",
            "",
            note.summary,
        ]
        
        if note.action_items:
            lines.append("")
            lines.append("**Actions:**")
            for item in note.action_items:
                lines.append(f"- [ ] {item}")
        
        return "\n".join(lines)
